USE [master]
GO

/****** Object:  Database [Taller]    Script Date: 01/04/2025 9:26:08 ******/
CREATE DATABASE [Taller]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Taller', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Taller.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Taller_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Taller_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Taller].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Taller] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Taller] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Taller] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Taller] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Taller] SET ARITHABORT OFF 
GO

ALTER DATABASE [Taller] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Taller] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Taller] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Taller] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Taller] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Taller] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Taller] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Taller] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Taller] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Taller] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Taller] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Taller] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Taller] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Taller] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Taller] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Taller] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Taller] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Taller] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Taller] SET  MULTI_USER 
GO

ALTER DATABASE [Taller] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Taller] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Taller] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Taller] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Taller] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Taller] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Taller] SET QUERY_STORE = ON
GO

ALTER DATABASE [Taller] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Taller] SET  READ_WRITE 
GO


